### ISSUE TITLE
Boost thread issue

### ISSUE THREAD

**Issue by varomix** [tangent-opensource/hdcycles#1]
I'm trying to build this and can't seem to get past this error
I built cycles separately and USD and those work, not sure why is failing to build USD when I run your build script, well cmake,
Am I missing something here?

This is on Windows

Thanks

`Adding boost_python dependencies: headers
CMake Error at E:/apps/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Could not find a package configuration file provided by "boost_thread"
  (requested version 1.70.0) with any of the following names:

    boost_threadConfig.cmake
    boost_thread-config.cmake`

**Comment by Vochsel** [comment]
Hi Varomix, 

Our current builds use boost-1.65.1 we haven't made the shift for HdCycles to boost-1.70.0, I suspect we will with newer versions of USD (We build against 19.11 and Houdini 18.0's USD build which is also 19.11)

If you still have issues with building against 1.65.1 feel free to reply here. 

Cheers

**Comment by varomix** [comment]
cool, I'll try using USD 19.11
is that in the read me? would be good to have that in the requirements
thanks

**Comment by Vochsel** [comment]
It is not explicitly no. We can look at putting that in the readme 👍

**Comment by varomix** [comment]
OK, trying with 1.65.1 now and I get the exact same error, USD builds using their build script fine

`Could NOT find Boost (missing: python27 thread filesystem) (found version "1.65.1")
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: thread filesystem) (found version "1.65.1")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  CMakeLists.txt:94 (find_package)`

**Comment by varomix** [comment]
not exactly the same error, can't find boost

**Comment by varomix** [comment]
OK, installed prebuilt boost libs and that works now, next issue
