### ISSUE TITLE
Conflict of libraries when building on Linux

### ISSUE THREAD

**Issue by kubo-von** [tangent-opensource/hdcycles#24]
Hello,
I'm trying to build hdcycles on PopOS! 20.04
Build seems to go well, all the dependencies are found, but then I get this:

```
-- Configuring done
CMake Warning at cmake/macros/Private.cmake:1130 (add_library):
  Cannot generate a safe runtime search path for target ndrCycles because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libtbbmalloc.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /media/colin/ssd/apps/HdCycles/deps/USD-19.11-build/lib
    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /media/colin/ssd/apps/HdCycles/deps/USD-19.11-build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/macros/Public.cmake:288 (_pxr_library)
  cmake/macros/Public.cmake:327 (pxr_library)
  plugin/ndrCycles/CMakeLists.txt:30 (pxr_plugin)


CMake Warning at cmake/macros/Private.cmake:1130 (add_library):
  Cannot generate a safe runtime search path for target hdCycles because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libtbbmalloc.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /media/colin/ssd/apps/HdCycles/deps/USD-19.11-build/lib
    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /media/colin/ssd/apps/HdCycles/deps/USD-19.11-build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/macros/Public.cmake:288 (_pxr_library)
  cmake/macros/Public.cmake:327 (pxr_library)
  plugin/hdCycles/CMakeLists.txt:30 (pxr_plugin)


-- Generating done
```

and the build of hdCycles and ndrcycles plugins does not finish.

Any idea what my problem might be ?
Thanks a lot.

(full terminal output attached)
[terminal.txt](https://github.com/tangent-opensource/hdcycles/files/5117070/terminal.txt)

**Comment by sherholz** [comment]
Hi @kubo-von 

you probably build USD via the provided build script didn't you?
If so USD downloads, and builds against it's own version of TBB.
This is where the conflict comes from.
The simplest way around it is to tel USD to use the TBB from your system.

Cheers,

Sebastian

**Comment by kubo-von** [comment]
Hi @sherholz 

Yes I did. That makes sense!
I guess then it might also be problem that I'm using USD which I've build on centos7 (couldn't get it to build on popOS/Ubuntu 20.04, PySide and Python 2 problems) I will try it again, and if I get it work I will try the system TBB this time.
Thanks a lot!

**Comment by kubo-von** [comment]
Building against system's TBB fixed this problem. Thanks!
Got another issue with pthread but probably not related to this, so closing :)
