### ISSUE TITLE
Build directory structure cannot be referenced directly

### ISSUE THREAD

**Issue by trebconnell** [tangent-opensource/hdcycles#7]
Would be nice for development iteration time if cmake install wasn't required to have files placed on disk in a structure that could be loaded.  Especially in Visual Studio where Install is an additional command must be run.

This could be fixed relatively easily by configuring the pluginfo into a resource folder.

Install would still work, but wouldn't be as necessary.

**Comment by trebconnell** [comment]
I plan to implement this...

**Comment by Vochsel** [comment]
Closing for now since our rez build process is preferred and in the process of being released. The needs of initial ticket are a bit vague, if future needs require this, more discussion can be had. 
Thanks!
