### ISSUE TITLE
Cannot build with embree enabled cycles

### ISSUE THREAD

**Issue by trebconnell** [tangent-opensource/hdcycles#9]
Need to link with embree libs

**Comment by Vochsel** [comment]
In the latest version of the repo, we now link against and have support for Embree if CMake finds it. 

https://github.com/tangent-opensource/hdcycles/blob/main/CMakeLists.txt#L164
https://github.com/tangent-opensource/hdcycles/blob/main/plugin/hdCycles/CMakeLists.txt#L38

Closing this issue for now
